# 管理群，只会响应该群内发送的/log消息
QQgroup: 963462616
fanserver: 1048699506

# 监听的ip和端口
host: localhost
port_ws: 8081
port_http: 3001

# 开头关键词，其余部分写在了风格文件
keyword: /

# 数据库、备份、图片、风格文件夹
db_name: database
backup_file: backup
image: static/images/logs
styles: styles
groups: static/images/groups

# 上次备份时间、备份周期、备份上限
backup_time: '2026-02-07 15:34:27'
backup_delay: 7
backup_limit: 10

# 当前风格文件名
style: normal

# qq重连周期
reconnect_delay: 30

# 网站session加密密钥
secret_key: "989c874b9e591a749f72a449c886b9167aaefe6160c56391fd87879757e5b15d"
